ingress:
  enabled: true
  path: /
  annotations:
    ## NOTE: Can't use 'false' due to https://github.com/jetstack/kube-lego/issues/173.
    kubernetes.io/ingress.allow-http: true
    kubernetes.io/ingress.class: nginx
    kubernetes.io/ingress.global-static-ip-name: ""
    kubernetes.io/tls-acme: false
  tls:
    enabled: false
    secretName: nexus-tls
  ## Specify custom rules in addition to or instead of the nexus-proxy rules
  rules:
  # - host: http://nexus.127.0.0.1.nip.io
  #   http:
  #     paths:
  #     - backend:
  #         serviceName: additional-svc
  #         servicePort: 80
  
## To use an additional service, set enable to true
service:
  # name: additional-svc
  enabled: false
  labels: {}
  annotations: {}
  ports:
  - name: nexus-service
    targetPort: 80
    port: 80
